<div class="table-row-group">
    <x-generic.table.contact-row
        firstname="Andrew"
        lastname="Garfield"
        email="andgar@gmail.com"
        image="andrew.jpg"
    />
    <x-generic.table.contact-row
        firstname="Navarette"
        lastname="Inde"
        email="navind@gmail.com"
        image="cat4.jpg"
    />
    <x-generic.table.contact-row
        firstname="Emma"
        lastname="Stone"
        email="emaastone@gmail.com"
        image="emmastone.jpg"
    />
    <x-generic.table.contact-row
        firstname="seren"
        lastname="coban"
        email="secobs@gmail.com"
        image="cat1.jpg"
    />
    <x-generic.table.contact-row
        firstname="Simge"
        lastname="Uzar"
        email="simguz@gmail.com"
        image="cat2.jpg"
    />
    <x-generic.table.contact-row
        firstname="Mark"
        lastname="Ruffaolo"
        email="markruf@gmail.com"
        image="mark.jpg"
    />
    <x-generic.table.contact-row
        firstname="Andrew"
        lastname="Garfield"
        email="andgar@gmail.com"
        image="andrew.jpg"
    />
    <x-generic.table.contact-row
        firstname="Navarette"
        lastname="Inde"
        email="navind@gmail.com"
        image="cat4.jpg"
    />
    <x-generic.table.contact-row
        firstname="Emma"
        lastname="Stone"
        email="emaastone@gmail.com"
        image="emmastone.jpg"
    />
    <x-generic.table.contact-row
        firstname="seren"
        lastname="coban"
        email="secobs@gmail.com"
        image="cat1.jpg"
    />
    <x-generic.table.contact-row
        firstname="Simge"
        lastname="Uzar"
        email="simguz@gmail.com"
        image="cat2.jpg"
    />
    <x-generic.table.contact-row
        firstname="Mark"
        lastname="Ruffaolo"
        email="markruf@gmail.com"
        image="mark.jpg"
    />


</div>
